---
title: "Experiencing suicidal thought: emotional bullied but continue to count my blessing"
content: "You might see the dark of someone until it blinds..."
category: "Blog"
subcategory: "Mental Blog"
img: "/assets/blog/experiencing-suicidal-thought/img.png"
meta: '/assets/blog/experiencing-suicidal-thought/meta.png'
date: "2021-10-31"
note: ""
---

## This is my story. “Experiencing suicidal thought: emotional bullied but continue to count my blessing.” 

To begin the story, I would like to claim that this is from my perspective. If any of you feel offended, please accept my apologies. I do not mean to reveal anyone here; instead, I just want to share my story hoping that it would inspire other people who had experienced such struggle like mine.  
 
I understand that everyone has his or her own struggle. Either it is big or small, the struggle is a struggle. As for me, my senior year of high school was the most unforgettable experience. I am just an ordinary girl who wanted to be an extraordinary girl. When I was a freshman, I really thought that I was so pretty, famous, and smart. This is because every time I went to the cafeteria, in the hallway around the school; there would be handsome guys that ask me to hang out with them. Not only that, but a lot of girls would also like to be my friends back then. Lastly, all the teachers loved me. Therefore, it made sense as I thought that I am extraordinary. However, my life started becoming upside down. It is all started with my curiosity. When I was 14 years old, I realize that almost everyone has a partner except for me. At that moment, I just really wanted to know the feeling of how amazing it is to have a special partner. Therefore, I decide to accept a random guy that I don’t even know that well. For sure, I know him as a bad boy who is always skipping classes, smoking, and playing around with girls. I know that I should not accept him, but from my perspective at that time, I just wanted to know the romantic feeling, and who know that I will be the special girl who was able to change him. Even if is not at least I will not feel guilty to dump him later since he was a bad boy. That is what I told myself.  
 
![illustrator_1](/assets/blog/experiencing-suicidal-thought/1.png "Azla Pic #1")

I never realize that times fly so fast. It’s been 4 months since I was being together with him. So far, I feel loved by him. It only lasts until, one random girl came and asked, “Is that guy your boyfriend?”. The conversation become so hot until it broke my heart. Unfortunately, my first boyfriend at that time was cheating on me behind my back. Without any further, I wanted confirmation from him. Of course, he said no. I try to ask all his friends but not even a single one dared to tell me the truth. Until one day I decided to spy on him, that was how I caught him redhanded. To shorten the story, I tried to break up with him, but he gave me his words that he will never repeat that again. I was in a toxic relationship for almost 2 years and a half. Not even a single day I feel secure. Almost every week I got a report that he was cheating behind my back.  

I started to realize that how much change happened to me. from a confident person into insecure, I do not feel pretty, not good enough. I start to dislike a lot of girls. The most event that hit me so bad almost to be happening. One day, my geography book was stolen by an unknown. I asked my boyfriend to wait for me on the fourth floor while I was searching for my textbook on the third floor where my class was located. Unfortunately, I failed and went to get my boyfriend. How unlucky I am, the teacher who dislike me assumed that we were dating and asked me to see him the next day. Because my face showed no guilty at all, I was sent to the discipline office and got suspended from school for 1 week. I was also asked to meet with a consulting teacher. The worst part, the week that I was suspended was the midterm week. I do not know what to do. I really feel hopeless at that moment. For you guys’ information. I am not really the kind of person who shares my feeling with my parents or even siblings. When I got suspended, I told my parents that our school was having sport even, therefore, I do not want to go to school. I think my parents were so trusted in me until they never question me any further. Of course, my aunt who works as a teacher at my school reported to my mom. I never forgot my mom's facial expression. She was crying while my dad was scolding me. I can’t help but hide my sad feeling. But instead of showing them how sad I am, I shouted to them and said, “there’s nothing bad happened and let me handle myself”. I decide to go to school the next day with my cousin's advice and help.  
Since that day, a lot of students were gossiping about me. even in the class, my name will always be brought up as a bad example by another teacher. Some of the teachers said “do not be like her, she comes to school just to get pregnant”; or “you don’t have to study so hard after you are done with high school you will just get yourself a husband”. While at home my brother took control or took over my phone. At the church, I feel like I was forced to participate without asking how I feel. To be honest, I already had my thought of suicide at the time. I keep comparing myself to my best friend and talking bad about her. I guess am just jealous.   
 
In December 2013, after I win convince my mom to transfer me to another school and break up with my boyfriend; I thought I could start a new life. I do not want to make a friend, I just wanted to focus on my study. My first week at the new school was fine for me. Until later on, my cousin told me almost everyone in the class did not like me. they even gossip about me in the WhatsApp group. At first, I thought it is wasn’t a big deal to me since I had already experienced that before. After 1 month, I started to get bullied by them. Not physically but emotionally; sometimes, I feel I was left out, and sometimes they were provoking me but I just act as if I was sleeping but actually, I was crying. I heard they gossip about me, still, I acted as nothing had happened. Sometimes they invited me to go cafeteria together, but I rejected the offers. Why? It is hard enough to act like I did not know anything, how on earth can I be strong enough to walk with them. I also started skipping school from then. I only went to school once or twice a week. If my parents ask me? I will try to make any excuses that I could. Of course, I got scolded by them. Since that was senior year, the homeroom teacher called me to meet her. Guess what, the teacher never asked about how I felt, or do I have any problem instead I suggested changing class since my grade was so bad but it is too late for that. To be honest, I did not even care about my grade anymore or either getting scolded by the teacher or family. I just really thought the world will be super happy if I die. Every day I was praying that God will take away my life. I still remember my pray “God, please take my life away, I do not want to kill myself so just kill me.” there were a lot of things happening at that time, until that night, I was ready to kill myself. I do not want to go to hell, but I can’t describe how I felt. The knife was ready on my right hand. Somehow, God's hand stopped me from continuing my plan.  
 
If you guys wonder whether I was okay at that time, to be honest, I was not sure. What happened to my national exam? I was doing so badly, I failed. since I did not study and skipped school, I only got 1 A, while I screwed up other subjects. if someone asked about my grade, I just lie to them that I got 7As. I know they would not believe me anyway but at least maybe that made me happy a bit. To be honest I was just so embarrassed about my grade. People started not to like me, maybe because I was rude or mean. I don’t know. I love to make sacrifices for them, but I never feel appreciated. I tried to share my story, they said “I feel sorry for you, it’s normal”. So I see, the thought about suicide is normal. When people asked “how are you?" On my mind, "what is on my mind? You ask if I am really okay or are you just asking? Do you really care about me? or are you going to use that against me? ahh, you are smiling at me? Is that genuine or do you just want to show other people on how perfect kind you are?” Readers, you might think I am overthinking, but I can’t help every time I thought the people like me, and I wanted to make a friend with them. But later on, I catch them red-handed. In front of me, they said “you are so lovely!" But behind me, they said that they do not like me. I respect that. When I wanted to be honest, I was claimed to be rude or mean girl. When I was laughing, they said that I am too loud. When I was praying or active at church, they said “you are too fake, I know your dark secret” I stop being active at church and started secretly doing devotional in my room, still I was told, “you forgot about your God; you wild.”  
People please, please. You might see the dark of someone until it blinds you to see other brightness. You might see others too bright until you never realize they are also normal human beings like you and you never see their struggle. We are judging others and think we are better than others. We try to fix other people's sins, but we forget to fix ourselves.  
 
![illustrator_2](/assets/blog/experiencing-suicidal-thought/2.png "Azla Pic #2")

People asked me “why you always alone”. Because you never asked what their story. Even though you asked are you willing to hear the story? Are you even read my story until the end? You see, in reality, the number of people who really care about you is less, but still, there is someone outside there who really cares about you. How to know that? Well, I don't have an answer to that because I am still searching for it.  

If you are struggling right now, please my love, stay strong and have faith in God's plans. I can not guarantee there is a happy ending like Disney princess but for sure I believe together we can win this battle without taking our own life. Please, if you are having a similar thought like me, do find some help. It will never be too late.  
